Repository opencrvs/opencrvs-farajaland, pull requests merged in 2022-04, with the labels that each got.

#211 ocrvs-2740: message added for form-config page
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: LGTM!, ready for merging

#206 Added new users
  backups/hearth-dev.gz
  backups/user-mgnt.gz
  src/farajaland/features/employees/source/test-employees.csv
Labels: Waiting For Review

#215 ocrvs 2722: Contents of form configuration summary page
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#214 Ocrvs 2690 Login language
  src/farajaland/config/login-config.js
  src/farajaland/config/login-config.prod.js
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-keys-to-migrate.json
  src/farajaland/features/languages/generated/client/descriptions.json
  src/farajaland/features/languages/generated/login/.gitignore
  src/farajaland/features/languages/generated/login/contentful-ids.json
  src/farajaland/features/languages/generated/login/contentful-keys-to-migrate.json
  src/farajaland/features/languages/generated/login/descriptions.json
  src/farajaland/features/languages/generated/login/login.json
  src/index.ts
Labels: Waiting For Review

#218 ocrvs-2722-fix: Added French translations
  src/farajaland/features/languages/generated/client/client.json
Labels: Waiting For Review

#221 ocrvs-2400-fix Added corrector id check dialog description
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: LGTM!

#224 ocrvs-2793 Removed Performance Oversight role from farajaland
  backups/user-mgnt.gz
  src/farajaland/features/employees/scripts/manage-users.ts
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#225 Ocrvs 2424 fix
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#216 Ocrvs 2740: intl messages added for form-config
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Conflicts, LGTM!

#232 Ocrvs 2773
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/contentful-keys-to-migrate.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#236 Birth and death form updates
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#239 OCRVS-2958 Added new messages for form config mobile view modal
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Waiting For Review
