Repository opencrvs/opencrvs-farajaland, pull requests merged in 2022-09, with the labels that each got.

#336 ocrvs-3332 Removed some unused messages
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#337 ocrvs-3732 Amend backup scripts to take version input
  emergency-backup-metadata.sh
  emergency-restore-metadata.sh
Labels: LGTM

#342 Migration hotfix
  emergency-restore-metadata.sh
Labels: LGTM!

#350 ocrvs-3977
  src/data-generator/queries.ts
Labels: Waiting For Review
