Repository opencrvs/opencrvs-farajaland, pull requests merged in 2022-02, with the labels that each got.

#142 ocrvs-2300 : Fix Cypress Test for all the test scripts
  cypress/downloads/February_2022_export.zip
  cypress/integration/birth.spec.ts
  cypress/integration/certificate.spec.ts
  cypress/integration/death.spec.ts
  cypress/integration/menu.spec.ts
  cypress/integration/performance.spec.ts
  cypress/integration/reports.spec.ts
  cypress/integration/search.spec.ts
  cypress/integration/user.spec.ts
  cypress/support/commands.js
  package.json
  yarn.lock
Labels: Waiting for fixes

#150 Build and push a version tagged container
  .github/workflows/publish-to-dockerhub.yml
  docker-compose.countryconfig.deploy.yml
  docker-compose.countryconfig.qa-deploy.yml
  docker-compose.yml
  package.json
Labels: LGTM

#119 OCRVS-2298: New open-him channel & application config
  backup-metadata.sh
  backups/application-config.gz
  backups/openhim-dev.gz
  clear-all-data.sh
  restore-metadata.sh
  src/farajaland/config/client-config.js
  src/farajaland/config/client-config.prod.js
  src/farajaland/config/login-config.js
  src/farajaland/config/login-config.prod.js
Labels: LGTM

#156 Added messages for correction summary page
  src/zmb/features/languages/generated/client/client.json
  src/zmb/features/languages/generated/client/contentful-ids.json
  src/zmb/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#160 Ocrvs-2496: applicant and contact page configuration change for birth and death application
  src/farajaland/features/forms/register.json
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: LGTM!

#144 Ocrvs 2405 Create backup having new openHIM channels
  backups/openhim-dev.gz
Labels: Waiting For Review

#155 ocrvs 2465 Certificate template backup merged with develop
  README.md
  backups/application-config.gz
  createReferenceData.sh
  docker-compose.countryconfig.deploy.yml
  src/constants.ts
  src/farajaland/features/config/model/certificate.ts
  src/farajaland/features/config/model/config.ts
  src/farajaland/features/config/scripts/populate-default-config.ts
  src/farajaland/features/definitions/handler.ts
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
  src/farajaland/features/templates/handler.ts
  src/farajaland/features/templates/register.json
  src/farajaland/features/templates/service.ts
Labels: Waiting for fixes

#161 Ocrvs 2575: fixed NID validation
  backups/application-config.gz
  src/farajaland/features/config/scripts/populate-default-config.ts
  src/farajaland/features/forms/register.json
Labels: LGTM

#157 ocrvs-2382 Added new header placeholder text
  src/farajaland/features/languages/generated/client/client.json
Labels: Waiting For Review

#149 ocrvs-1909-latest Added MaxLength in register json for name input
  src/farajaland/features/forms/register.json
Labels: Waiting For Review

#171 ocrvs-1909 Added data limit to father and spouse name
  src/farajaland/features/forms/register.json
Labels: Waiting For Review

#164 If environment is production, populated users must create security questions and change password
  src/farajaland/features/employees/scripts/assign-employees-to-practitioners.ts
  src/farajaland/features/employees/scripts/service/index.ts
Labels: Waiting For Review

#146 ocrvs 2519 Correction Flow
  src/farajaland/features/forms/register.json
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Waiting For Review
