Repository opencrvs/opencrvs-farajaland, pull requests merged in 2022-10, with the labels that each got.

#359 removed the deprecated --update-metadata flag from the deploy.yml
  .github/workflows/deploy.yml
Labels: LGTM!

#364 updated client message info
  src/features/languages/generated/client/client.json
Labels: Waiting for fixes

#367 ocrvs-3927 add field id section on the right side nav in form config
  src/features/languages/generated/client/client.json
Labels: ready for merging

#371 ocrvs-4068-fix Added missing intl messages
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#370 Ocrvs -3926 - Change label name to "Has a cause of death been established?"
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: LGTM!

#358 Run extract translations on `ocrvs-3983-workqueue-a11y`
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#372 Ocrvs 3126 - Form radio buttons should be Checkbox's
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#381 Ocrvs 4105 frontend
  cypress/support/commands.ts
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#327 [1.0.3] OCRVS-3673: Introduced new feature: Notification
  Dockerfile
  docker-compose.countryconfig.demo-deploy.yml
  docker-compose.countryconfig.prod-deploy.yml
  package.json
  src/features/notification/constant.ts
  src/features/notification/handler.ts
  src/features/notification/service.ts
  src/index.ts
  yarn.lock
Labels: LGTM!, 📄Documentation

#376 ocrvs-4039 Reset user password messages
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
  src/features/languages/generated/notification/contentful-ids.json
  src/features/languages/generated/notification/descriptions.json
  src/features/languages/generated/notification/notification.json
Labels: Waiting For Review

#356 ocrvs-3684 Fetched declaration only before initiating status change
  .eslintrc.js
  src/data-generator/index.ts
Labels: Waiting For Review

#345 ocrvs-n-3640: User Audit new messages
  cypress/support/commands.ts
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/descriptions.json
Labels: Conflicts, Waiting for fixes

#386 ocrvs-4004: Add translations for zero documents when review scroll is disabled
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#388 ocrvs-4120: Add translations for viewed regAction
  src/features/languages/generated/client/client.json
Labels: Waiting For Review

#365 Feature: Vital Statistics Export
  clear-all-data.sh
  emergency-backup-metadata.sh
  emergency-restore-metadata.sh
  restore-metadata.sh
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: LGTM
