Repository opencrvs/opencrvs-farajaland, pull requests merged in 2022-06, with the labels that each got.

#278 Add fonts with svg
  backups/application-config.gz
  src/features/config/scripts/birth-certificate-template-default.ts
  src/features/config/scripts/death-certificate-template-default.ts
  src/features/config/scripts/fonts/noto-sans.ts
Labels: 💥 Hot Fixes

#285 Added changeLanguageMessage
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/descriptions.json
Labels: question, LGTM!

#296 ocrvs-2556 Fixed govtLogoChangeMessage typo
  src/features/languages/generated/client/client.json
Labels: Waiting For Review

#300 Added content messages for total payment label in correction summary…
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#310 ocrvs-3488: noResultFor message added for no result in search
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
Labels: Waiting For Review

#311 ocrvs-2977-new-fix Fixed some french lang issue
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
Labels: Waiting For Review

#315 Validate CSV files used for populating the database before starting
  createReferenceData.sh
  package.json
  src/data-generator/certify.ts
  src/features/administrative/statistics.ts
  src/scripts/validate-source-files.ts
  src/utils/index.ts
  tsconfig.json
  yarn.lock
Labels: Waiting For Review
