Repository opencrvs/opencrvs-farajaland, pull requests merged in 2022-12, with the labels that each got.

#416 ocrvs-4117 Advanced Search Bookmark Messages
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#382 Feature - Advance Search
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#425 ocrvs-4309-fix Modified some messages id for common content key
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
Labels: Waiting For Review

#432 Validate sensicality of locations in import script
  .eslintrc.js
  src/scripts/humdata-validation.ts
  src/scripts/validate-source-files.ts
Labels: LGTM

#437 Fixed data-generator
  graphql.schema.json
  src/data-generator/declare.ts
  src/data-generator/gateway.ts
  src/data-generator/index.ts
  src/data-generator/queries.ts
Labels: Waiting For Review

#426 team cypress test fix & reset password, username reminder test added
  cypress/integration/team.spec.ts
  cypress/support/commands.ts
Labels: Waiting For Review

#441 Integration fixes
  postman/Authenticate.postman_collection.json
  postman/Event Notification.postman_collection.json
  postman/Location.postman_collection.json
  postman/OpenCRVS.postman_globals.json
  postman/Production.postman_environment.json
  postman/Record Search.postman_collection.json
  postman/Webhook.postman_collection.json
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#434 ocrvs-4307: label changes and missing description
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#417 Informant signature: Updated messages and french translations
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: on hold

#444 OCRVS-4433: We need to make sure that default backups do not have run migrations in them
  backup-metadata.sh
  backups/application-config.gz
  backups/hearth-dev.gz
  backups/openhim-dev.gz
  backups/user-mgnt.gz
  clear-all-data.sh
  create-backup.sh
  package.json
  restore-backup.sh
  restore-metadata.sh
  yarn.lock
Labels: 📄Documentation
