Repository opencrvs/opencrvs-farajaland, pull requests merged in 2022-01, with the labels that each got.

#110 ocrvs-2299 Removed jurisdiction names from districts and provinces
  backups/hearth-dev.gz
  backups/openhim-dev.gz
  backups/user-mgnt.gz
  src/zmb/features/administrative/source/districts.csv
  src/zmb/features/administrative/source/provinces.csv
  src/zmb/features/languages/generated/client/client.json
  src/zmb/features/languages/generated/client/contentful-ids.json
  src/zmb/features/languages/generated/client/descriptions.json
Labels: LGTM

#114 ocrvs-1966 Change user deactivate and reactivate form error message
  src/zmb/features/languages/generated/client/client.json
Labels: Waiting For Review, LGTM

#115 Ocrvs 1904 Changes condition and name for Add file
  src/zmb/features/forms/index.ts
  src/zmb/features/forms/user/userSection.ts
  src/zmb/features/forms/utils.ts
  src/zmb/features/languages/generated/client/client.json
Labels: LGTM

#121 ocrvs-2336 Added message descriptions for DNRPC type
  src/zmb/features/languages/generated/client/client.json
  src/zmb/features/languages/generated/client/contentful-ids.json
  src/zmb/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#130 CRA upgrade
  src/index.ts
Labels: Waiting For Review

#116 ocrvs-1618 Change profile image
  src/zmb/features/languages/generated/client/client.json
  src/zmb/features/languages/generated/client/contentful-ids.json
  src/zmb/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#140 ocrvs-2393: default value added for documentForWhom json
  src/zmb/features/languages/generated/client/client.json
Labels: LGTM
