Repository opencrvs/opencrvs-farajaland, pull requests merged in 2022-05, with the labels that each got.

#251 Update backups with new Performance manager user
  backups/hearth-dev.gz
  backups/user-mgnt.gz
  src/farajaland/features/employees/scripts/manage-users.ts
  src/farajaland/features/employees/source/test-employees.csv
Labels: Waiting for fixes

#242 Ocrvs 2915
  src/farajaland/features/languages/generated/client/client.json
Labels: Waiting for fixes

#240 ocrvs-2836: Updated messages for records of status table
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: ready for merging

#266 Ocrvs 3089
  backups/hearth-dev.gz
  backups/user-mgnt.gz
  src/farajaland/features/employees/model/user.ts
  src/farajaland/features/employees/source/test-employees.csv
  src/farajaland/features/languages/generated/client/client.json
  src/farajaland/features/languages/generated/client/contentful-ids.json
  src/farajaland/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#267 Improve server setup docs
  .github/workflows/publish-to-dockerhub.yml
Labels: Waiting For Review

#268 Fixed cypress duplicate mobile number issue
  cypress.json
  cypress/integration/user.spec.ts
  cypress/support/commands.ts
  package.json
Labels: Waiting For Review

#271 Modified certificate update messages
  src/features/languages/generated/client/client.json
  src/features/languages/generated/client/contentful-ids.json
  src/features/languages/generated/client/contentful-keys-to-migrate.json
  src/features/languages/generated/client/descriptions.json
Labels: Waiting For Review

#276 ocrvs-2743: Added translation with file validation in client-config.js
  src/features/languages/generated/client/client.json
  src/index.ts
Labels: question
