Repository opencrvs/opencrvs-farajaland, pull requests merged in 2023-10, with the labels that each got.

#743 Hotfix: Fix backing up ElasticSearch data
  infrastructure/emergency-backup-metadata.sh
Labels: 💥 Hot Fixes

#684 [OCRVS-3601] Correction approval from Registration agents
  infrastructure/docker-compose.replicas-3.yml
  infrastructure/docker-compose.replicas-5.yml
  src/api/content/client/client.json
  src/api/notification/email-service.ts
  src/api/notification/email-templates/other/correction-approved.html
  src/api/notification/email-templates/other/correction-rejected.html
Labels: Waiting For Review

#685 email message add for search
  src/api/content/client/client.json
  src/api/content/client/descriptions.json
Labels: on hold

#762 id verifier message add for age
  src/api/content/client/client.json
  src/api/content/client/descriptions.json
Labels: Waiting For Review

#761 ocrvs-6063 Include type parameter in name query
  postman/Location.postman_collection.json
Labels: 💥 Hot Fixes

#754 Ocrvs 5794 - configuration of signatures for users
  src/api/application/application-config-default.ts
  src/data-seeding/certificates/source/test/UsingSignatureHandlebars.svg
  src/utils/mapping/section/birth/mapping-utils.ts
Labels: documentation, 💥 Hot Fixes

#757 Ocrvs 5994- certificate collector options fix
  src/api/content/client/client.json
  src/api/content/client/descriptions.json
  src/form/common/select-options.ts
Labels: 💥 Hot Fixes

#756 Ocrvs 6032
  infrastructure/docker-compose.deploy.yml
Labels: 💥 Hot Fixes

#745 Requirements for Niue
  src/form/death/certficate-handlebars.ts
Labels: 💥 Hot Fixes

#769 fix message for collector form
  src/api/content/client/client.json
Labels: Waiting For Review

#765 feat: inform client which administrative level is leaf level
  src/form/addresses/address-fields.ts
  src/form/addresses/index.ts
  src/form/types/types.ts
  src/form/types/validators.ts
  src/utils/address-utils.ts
Labels: 📄Documentation

#771 messages fix for send for approval button
  src/api/content/client/client.json
Labels: Waiting For Review
