Repository opencrvs/opencrvs-farajaland, pull requests merged in 2023-08, with the labels that each got.

#647 Ocrvs 5572 fix
  src/features/notification/email-service.ts
Labels: Waiting For Review

#649 Feature: data seeding
  .github/workflows/deploy.yml
  .github/workflows/seed-data.yml
  infrastructure/deploy.sh
  infrastructure/restore-metadata.sh
  infrastructure/run-migrations.sh
  package.json
  src/features/administrative/scripts/utils/index.ts
  src/features/certificates/BirthCertificate.svg
  src/features/certificates/DeathCertificate.svg
  src/features/certificates/MarriageCertificate.svg
  src/features/certificates/handler.ts
  src/features/config/application/apllication-config-default.ts
  src/features/config/application/handler.ts
  src/features/employees/handler.ts
  src/features/employees/source/default-employee.csv
  src/features/locations/crvs-facilities.csv
  src/features/locations/handler.ts
  src/features/locations/health-facilities.csv
  src/features/locations/locations.csv
  src/features/roles/handler.ts
  src/features/roles/roles.csv
  src/features/roles/validator.ts
  src/index.ts
Labels: Waiting For Review

#652 Fixed informant email notification
  src/email-templates/birth/inProgress.html
  src/features/notification/email-service.ts
Labels: Waiting For Review

#661 brn drn messages update
  src/api/content/client/client.json
  src/api/content/client/descriptions.json
Labels: ready for merging

#662 fix name of application config
  src/api/application/application-config-default.ts
  src/api/application/handler.ts
  src/index.ts
Labels: ready for merging

#583 update patient identifier with codeableConcept type
  postman/Event Notification.postman_collection.json
  src/api/mediators/mosip-openhim-mediator/handler.ts
Labels: Waiting For Review

#659 Modifed marital status field visibility for death
  src/form/birth/index.ts
  src/form/common/common-optional-fields.ts
  src/form/death/index.ts
Labels: Waiting For Review

#663 refactor birth forms dividers
  src/form/addresses/address-utils.ts
  src/form/addresses/index.ts
  src/form/birth/index.ts
  src/form/birth/optional-fields.ts
  src/form/birth/required-fields.ts
  src/form/common/common-optional-fields.ts
  src/form/death/index.ts
  src/form/death/required-fields.ts
  src/form/marriage/index.ts
Labels: Waiting For Review

#634 (data-generator): generate various attachment types instead of only one
  graphql.schema.json
  src/data-generator/address.ts
  src/data-generator/birthNotification.ts
  src/data-generator/certify.ts
  src/data-generator/declare.ts
  src/data-generator/gateway.ts
  src/data-generator/issue.ts
  src/data-generator/location.ts
  src/data-generator/options.ts
  src/data-generator/queries.ts
  src/data-generator/register.ts
  src/data-generator/users.ts
  src/form/types/types.ts
  src/form/types/validators.ts
  src/utils/index.ts
Labels: Waiting For Review

#664 certificate template update
  src/data-seeding/certificates/source/BirthCertificate.svg
  src/data-seeding/certificates/source/DeathCertificate.svg
Labels: Waiting For Review

#673 Fix postman json for health notification
  postman/Event Notification.postman_collection.json
Labels: Waiting For Review

#674 Restart openhim after running migrations
  .github/workflows/seed-data.yml
  clear-all-data.sh
  infrastructure/run-migrations.sh
Labels: Waiting For Review

#677 email field type fix
  src/form/common/common-optional-fields.ts
Labels: Waiting For Review

#680 Rename seed vars, deprecate old secrets
  .github/workflows/generate-demo-data.yml
  .github/workflows/seed-data.yml
  infrastructure/deploy.sh
  infrastructure/docker-compose.countryconfig.demo-deploy.yml
  infrastructure/docker-compose.countryconfig.mosip-example-deploy.yml
  infrastructure/docker-compose.countryconfig.prod-deploy.yml
  infrastructure/docker-compose.countryconfig.qa-deploy.yml
  infrastructure/docker-compose.countryconfig.staging-deploy.yml
  src/data-generator/auth.ts
  src/data-generator/certify.ts
  src/data-generator/constants.ts
  src/data-generator/declare.ts
  src/data-generator/issue.ts
  src/data-generator/location.ts
  src/data-generator/register.ts
  src/data-generator/reject.ts
  src/data-generator/statistics.ts
  src/data-generator/users.ts
Labels: Waiting For Review

#679 witness section fix
  src/form/marriage/required-fields.ts
Labels: Waiting For Review

#678 correction id verifier message add
  src/api/content/client/client.json
  src/api/content/client/descriptions.json
Labels: LGTM!
