Repository opencrvs/opencrvs-farajaland, pull requests merged in 2023-03, with the labels that each got.

#467 ocrvs-4512: Setting the role of a user randomly from fetched systemRoles
  graphql.schema.json
  src/data-generator/gateway.ts
  src/data-generator/queries.ts
  src/data-generator/users.ts
  src/features/employees/scripts/utils/index.ts
Labels: on hold

#490 ocrvs-4641 Added marriage event declaration form massages
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
  src/features/utils/index.ts
Labels: Waiting For Review

#512 feat(national-id-verification): add offline translations and remove loading translation
  src/features/languages/content/client/client.json
  src/features/languages/content/client/descriptions.json
Labels: Waiting For Review

#504 Marriage certificate configuration messages
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: Waiting For Review

#469 Feature - Potential duplicates by registrars
  cypress/integration/death.spec.ts
  cypress/support/commands.ts
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: Waiting For Review

#479 OCRVS-4638: System client name taken from random health facility name data generator
  src/data-generator/birthNotification.ts
  src/data-generator/declare.ts
  src/data-generator/users.ts
Labels: ready for merging

#488 Remove migrate-mongo as it's not needed after #4682
  package.json
  yarn.lock
Labels: Waiting For Review

#511 Change MOSIP_UINTOKEN to MOSIP_PSUT_TOKEN_ID
  src/features/mediators/mosip-openhim-mediator/handler.ts
Labels: Waiting For Review

#501 [Feature] Add analytics dashboards for admins and performance manager
  emergency-backup-metadata.sh
  emergency-restore-metadata.sh
  src/client-configs/client-config.js
  src/client-configs/client-config.prod.js
  src/features/languages/content/client/client.json
Labels: Conflicts

#515 Deprecate country-data from Farajaland
  package.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
  src/features/utils/countryUtils.ts
  src/features/utils/index.ts
  typings/country-data.d.ts
Labels: Waiting for fixes
