Repository opencrvs/opencrvs-farajaland, pull requests merged in 2023-07, with the labels that each got.

#604 Build TS validators and conditionals to JS & deprecate Contentful
  .vscode/settings.json
  dev.sh
  package.json
  src/constants.ts
  src/data-generator/index.ts
  src/data-generator/util.ts
  src/features/administrative/scripts/import-default-config-and-admin-structure.ts
  src/features/administrative/scripts/import-statistics.ts
  src/features/administrative/scripts/utils/index.ts
  src/features/administrative/service/service.ts
  src/features/config/form/address-utils.ts
  src/features/config/form/addresses.ts
  src/features/config/form/birth.ts
  src/features/config/form/birth/optional-fields.ts
  src/features/config/form/birth/preview-groups.ts
  src/features/config/form/birth/required-fields.ts
  src/features/config/form/birth/utils.ts
  src/features/config/form/conditionals-handler.ts
  src/features/config/form/conditionals.ts
  src/features/config/form/death.ts
  src/features/config/form/index.ts
  src/features/config/form/marriage.ts
  src/features/config/form/options.ts
  src/features/config/form/types/types.ts
  src/features/config/form/types/validators.ts
  src/features/config/form/validators-handler.ts
  src/features/config/form/validators.js
  src/features/config/form/validators.ts
  src/features/languages/content/client/.gitignore
  src/features/languages/content/client/contentful-ids.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/opencrvs.code-workspace
  src/features/languages/content/login/.gitignore
  src/features/languages/content/login/contentful-ids.json
  src/features/languages/content/login/contentful-keys-to-migrate.json
  src/features/languages/content/notification/.gitignore
  src/features/languages/content/notification/contentful-ids.json
  src/features/languages/content/notification/contentful-keys-to-migrate.json
  src/features/languages/scripts/constants.ts
  src/features/languages/scripts/contentful-template.ts
  src/features/languages/scripts/contentfulImport.ts
  src/features/languages/service/service.ts
  src/features/utils/index.ts
  src/index.ts
  src/scripts/humdata-validation.ts
  src/scripts/validate-source-files.ts
  tsconfig.json
  yarn.lock
Labels: Waiting For Review

#607 Upgrade Traefik to v2.9 to upgrade default minimum TLS to 1.2
  infrastructure/docker-compose.deploy.yml
Labels: Waiting For Review

#584 Create ocrvs elastic index during deploy
  infrastructure/elasticsearch/setup-helpers.sh
  infrastructure/elasticsearch/setup-settings.sh
  infrastructure/restore-metadata.sh
Labels: LGTM!

#606 ocrvs-5538 Create route for serving locations metadata
  src/features/administrative/scripts/utils/index.ts
  src/features/locations/crvs-facilities.csv
  src/features/locations/handler.ts
  src/features/locations/health-facilities.csv
  src/features/locations/locations.csv
  src/index.ts
Labels: Waiting For Review

#609 ocrvs 5514-death form refactor
  src/features/config/form/addresses.ts
  src/features/config/form/birth.ts
  src/features/config/form/birth/optional-fields.ts
  src/features/config/form/birth/required-fields.ts
  src/features/config/form/birth/utils.ts
  src/features/config/form/common-optional-fields.ts
  src/features/config/form/common-required-fields.ts
  src/features/config/form/common-utils.ts
  src/features/config/form/death.ts
  src/features/config/form/death/required-fields.ts
  src/features/config/form/formatjs-messages.ts
  src/features/config/form/marriage.ts
  src/features/config/form/marriage/optional-fields-marriage.ts
  src/features/config/form/marriage/required-fields-marriage.ts
  src/features/config/form/marriage/utils.ts
  src/features/config/form/options.ts
  src/features/languages/content/client/client.json
Labels: Waiting for fixes

#618 Fixed marriage declaration form
  src/features/config/form/birth.ts
  src/features/config/form/common-required-fields.ts
  src/features/config/form/death.ts
  src/features/config/form/marriage.ts
  src/features/config/form/marriage/required-fields-marriage.ts
Labels: Waiting For Review

#610 seeding application config
  src/features/config/application/apllication-config-default.ts
  src/features/config/application/handler.ts
  src/index.ts
Labels: Conflicts, LGTM!

#625 Added email template and Send informant email
  infrastructure/docker-compose.countryconfig.demo-deploy.yml
  infrastructure/docker-compose.countryconfig.prod-deploy.yml
  infrastructure/docker-compose.countryconfig.qa-deploy.yml
  infrastructure/docker-compose.countryconfig.staging-deploy.yml
  src/client-configs/client-config.js
  src/client-configs/login-config.js
  src/email-templates/birth/inProgress.html
  src/email-templates/birth/inReview.html
  src/email-templates/birth/registration.html
  src/email-templates/birth/rejection.html
  src/email-templates/death/inProgress.html
  src/email-templates/death/inReview.html
  src/email-templates/death/registration.html
  src/email-templates/death/rejection.html
  src/email-templates/marriage/inProgress.html
  src/email-templates/marriage/inReview.html
  src/email-templates/marriage/registration.html
  src/email-templates/marriage/rejection.html
  src/email-templates/other/2-factor-authentication.html
  src/email-templates/other/change-email-address.html
  src/email-templates/other/change-phone-number.html
  src/email-templates/other/onboarding-invite.html
  src/email-templates/other/password-reset-by-system-admin.html
  src/email-templates/other/password-reset.html
  src/email-templates/other/username-reminder.html
  src/email-templates/other/username-updated.html
  src/features/config/form/common-optional-fields.ts
  src/features/languages/content/client/client.json
  src/features/notification/constant.ts
  src/features/notification/email-service.ts
  src/features/notification/handler.ts
Labels: Waiting For Review

#638 Fix copy issues
  src/features/config/form/formatjs-messages.ts
  src/features/config/form/marriage.ts
  src/features/languages/content/client/client.json
Labels: 🚧 work in progress
