Repository opencrvs/opencrvs-farajaland, pull requests merged in 2023-05, with the labels that each got.

#535 Signature file size error messages
  src/data-generator/constants.ts
  src/data-generator/index.ts
  src/data-generator/users.ts
  src/data-generator/vsExport.ts
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: Waiting For Review

#544 Allow validating CSV files without all higher levels of administration
  src/scripts/validate-source-files.ts
Labels: Waiting For Review

#562 Add USER_NOTIFICATION_DELIVERY_METHOD in docker-compose files and add translations for email error toast
  docker-compose.countryconfig.demo-deploy.yml
  docker-compose.countryconfig.prod-deploy.yml
  docker-compose.countryconfig.qa-deploy.yml
  docker-compose.countryconfig.staging-deploy.yml
  src/client-configs/client-config.js
  src/client-configs/client-config.prod.js
  src/client-configs/login-config.js
  src/client-configs/login-config.prod.js
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: ready for merging

#493 feat: National ID verification
  docker-compose.countryconfig.demo-deploy.yml
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
  src/features/mediators/mosip-openhim-mediator/handler.ts
Labels: 🚧 work in progress

#483 Changing the scripts with named parameters
  .github/workflows/deploy.yml
  emergency-backup-metadata.sh
  emergency-restore-metadata.sh
Labels: Waiting For Review
