Repository opencrvs/opencrvs-farajaland, pull requests merged in 2023-01, with the labels that each got.

#456 Ensure metrics database and webhooks database backs up
  clear-all-data.sh
  emergency-backup-metadata.sh
  emergency-restore-metadata.sh
Labels: Waiting For Review

#445 Added new messages for informant sms notification
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: Waiting For Review

#455 Changes vsExport messages
  emergency-backup-metadata.sh
  emergency-restore-metadata.sh
  src/features/languages/content/client/client.json
Labels: Waiting For Review

#461 ocrvs-4445 User Roles Config Messages
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: Waiting For Review

#464 Added new messages for Duplicate declarations
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: 🚧 work in progress

#446 Feature/informant signature
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-ids.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: Conflicts

#474 ocrvs-4469 Duplicate declaration comparison messages
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
Labels: 🚧 work in progress
