Repository opencrvs/opencrvs-farajaland, pull requests merged in 2023-06, with the labels that each got.

#572 Add translations for email related changes in username reminder and password reset flow
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
  src/features/languages/content/login/contentful-keys-to-migrate.json
  src/features/languages/content/login/descriptions.json
  src/features/languages/content/login/login.json
Labels: ready for merging

#569 move deployment infrastructure from Core to Farajaland
  .github/workflows/deploy.yml
  infrastructure/clear-all-data.sh
  infrastructure/cryptfs/bootstrap.sh
  infrastructure/cryptfs/mount.sh
  infrastructure/cryptfs/umount.sh
  infrastructure/decrypt.sh
  infrastructure/deploy.sh
  infrastructure/docker-compose.countryconfig.demo-deploy.yml
  infrastructure/docker-compose.countryconfig.prod-deploy.yml
  infrastructure/docker-compose.countryconfig.qa-deploy.yml
  infrastructure/docker-compose.countryconfig.replicas-1.yml
  infrastructure/docker-compose.countryconfig.replicas-3.yml
  infrastructure/docker-compose.countryconfig.replicas-5.yml
  infrastructure/docker-compose.countryconfig.staging-deploy.yml
  infrastructure/docker-compose.deploy.yml
  infrastructure/docker-compose.prod-deploy.yml
  infrastructure/docker-compose.qa-deploy.yml
  infrastructure/docker-compose.replicas-3.yml
  infrastructure/docker-compose.replicas-5.yml
  infrastructure/docker-compose.staging-deploy.yml
  infrastructure/elasticsearch/jvm.options
  infrastructure/elasticsearch/roles/kibana_user.json
  infrastructure/elasticsearch/roles/search_user.json
  infrastructure/elasticsearch/setup-helpers.sh
  infrastructure/elasticsearch/setup-settings.sh
  infrastructure/elasticsearch/setup-users.sh
  infrastructure/elasticsearch/setup.sh
  infrastructure/emergency-backup-metadata.sh
  infrastructure/emergency-restore-metadata.sh
  infrastructure/hearth-plugins/checkDuplicateTask.js
  infrastructure/hearth-queryparam-extensions.json
  infrastructure/influxdb.conf
  infrastructure/logrotate.conf
  infrastructure/mongodb/README.md
  infrastructure/mongodb/on-deploy.sh
  infrastructure/monitoring/apm/apm-server.yml
  infrastructure/monitoring/beats/metricbeat.yml
  infrastructure/monitoring/beats/rollover-policy.json
  infrastructure/monitoring/elastalert/elastalert.yaml
  infrastructure/monitoring/elastalert/rules/alert.yaml
  infrastructure/monitoring/elastalert/rules/auth.yaml
  infrastructure/monitoring/kibana/config.ndjson
  infrastructure/monitoring/kibana/kibana.yml
  infrastructure/monitoring/logstash/logstash.conf
  infrastructure/monitoring/logstash/logstash.yml
  infrastructure/openhim-base-config.json
  infrastructure/openhim-console-config.deploy.json
  infrastructure/openhim-console-config.json
  infrastructure/restore-metadata.sh
  infrastructure/rotate-secrets.sh
  infrastructure/server-setup/example-1.ini
  infrastructure/server-setup/example-3.ini
  infrastructure/server-setup/example-5.ini
  infrastructure/server-setup/group_vars/all.yml
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  infrastructure/setup-deploy-config.sh
  package.json
Labels: ready for merging

#571 ocrvs 5376 Added 2022 & 2023 statistic data
  backups/hearth-dev.gz
  backups/user-mgnt.gz
  graphql.schema.json
  src/data-generator/gateway.ts
  src/data-generator/statistics.ts
  src/features/administrative/source/farajaland-statistics.csv
Labels: Waiting For Review

#568 added Itambo district office and updated backup zips
  backups/hearth-dev.gz
  backups/user-mgnt.gz
  src/features/facilities/source/crvs-facilities.csv
Labels: Waiting for fixes

#573 fix data-generator querying fields with old schema
  src/data-generator/users.ts
Labels: Waiting For Review

#558 Feature: Email 2FA etc
  .github/workflows/deploy.yml
  README.md
  graphql.schema.json
  infrastructure/deploy.sh
  infrastructure/docker-compose.countryconfig.demo-deploy.yml
  infrastructure/docker-compose.countryconfig.prod-deploy.yml
  infrastructure/docker-compose.countryconfig.qa-deploy.yml
  infrastructure/docker-compose.countryconfig.staging-deploy.yml
  package.json
  src/client-configs/client-config.js
  src/client-configs/client-config.prod.js
  src/client-configs/login-config.js
  src/client-configs/login-config.prod.js
  src/constants.ts
  src/data-generator/gateway.ts
  src/email-templates/2-factor-authentication.html
  src/email-templates/change-email-address.html
  src/email-templates/change-phone-number.html
  src/email-templates/onboarding-invite.html
  src/email-templates/password-reset-by-system-admin.html
  src/email-templates/password-reset.html
  src/email-templates/username-reminder.html
  src/email-templates/username-updated.html
  src/features/countryLogo/handler.ts
  src/features/languages/content/client/client.json
  src/features/languages/content/client/contentful-keys-to-migrate.json
  src/features/languages/content/client/descriptions.json
  src/features/languages/content/login/contentful-keys-to-migrate.json
  src/features/languages/content/login/descriptions.json
  src/features/languages/content/login/login.json
  src/features/notification/constant.ts
  src/features/notification/email-service.ts
  src/features/notification/handler.ts
  src/features/notification/service.ts
  src/features/notification/sms-service.ts
  src/features/utils/index.ts
  src/index.ts
  yarn.lock
Labels: on hold

#593 Remove country_config_path and Farajaland playbook.yml
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  playbook.yml
Labels: documentation

#595 add country name in gateway environment in the docker-compose.countryconfig.*.yml files
  infrastructure/docker-compose.countryconfig.demo-deploy.yml
  infrastructure/docker-compose.countryconfig.prod-deploy.yml
  infrastructure/docker-compose.countryconfig.qa-deploy.yml
  infrastructure/docker-compose.countryconfig.staging-deploy.yml
Labels: documentation
