Repository opencrvs/opencrvs-farajaland, pull requests merged in 2024-08, with the labels that each got.

#1077 E2e/fix
  e2e/assets/528KB-random.png
  e2e/helpers.ts
  e2e/testcases/birth/declarations/birth-declaration-3.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-7.spec.ts
  e2e/testcases/death/declaration/death-declaration-2.spec.ts
  e2e/testcases/death/declaration/death-declaration-4.spec.ts
  e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
  e2e/testcases/marriage/6-details-page-validation.spec.ts
Labels: Waiting For Review

#1025 feat: record correction - ( birth, death )
  e2e/helpers.ts
  e2e/testcases/applications/.gitkeep
  e2e/testcases/applications/17-validate-user-can-correct-a-record-from-audit-record-page.spec.ts
  e2e/testcases/applications/correction/correct-record-1.spec.ts
  e2e/testcases/applications/correction/correct-record-10.spec.ts
  e2e/testcases/applications/correction/correct-record-11.spec.ts
  e2e/testcases/applications/correction/correct-record-12.spec.ts
  e2e/testcases/applications/correction/correct-record-13.spec.ts
  e2e/testcases/applications/correction/correct-record-14.spec.ts
  e2e/testcases/applications/correction/correct-record-15.spec.ts
  e2e/testcases/applications/correction/correct-record-16.spec.ts
  e2e/testcases/applications/correction/correct-record-17.spec.ts
  e2e/testcases/applications/correction/correct-record-18.spec.ts
  e2e/testcases/applications/correction/correct-record-2.spec.ts
  e2e/testcases/applications/correction/correct-record-3.spec.ts
  e2e/testcases/applications/correction/correct-record-4.spec.ts
  e2e/testcases/applications/correction/correct-record-5.spec.ts
  e2e/testcases/applications/correction/correct-record-6.spec.ts
  e2e/testcases/applications/correction/correct-record-7.spec.ts
  e2e/testcases/applications/correction/correct-record-8.spec.ts
  e2e/testcases/applications/correction/correct-record-9.spec.ts
  e2e/testcases/birth/helpers.ts
  e2e/testcases/birth/queries.ts
  e2e/testcases/birth/types.ts
  e2e/testcases/death/helpers.ts
  e2e/testcases/death/queries.ts
  e2e/testcases/death/types.ts
Labels: ready for merging

#1068 (For configurable roles) update files for default users
  src/data-seeding/employees/source/default-employees.csv
  src/data-seeding/roles/roles.json
Labels: ready for merging, 👨‍👩‍👦 User roles

#1089 ignore unavailable indices upon delete
  infrastructure/elasticsearch/setup-elastalert-indices.sh
Labels: ready for merging

#1092 Fix/add test case for changes to review declaration
  e2e/testcases/birth/8-validate-declaration-review-page.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-1.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-10.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-2.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-3.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-4.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-5.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-6.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-7.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-8.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-9.spec.ts
  e2e/testcases/death/8-validate-declaration-review-page.spec.ts
  e2e/testcases/death/declaration/death-declaration-1.spec.ts
  e2e/testcases/death/declaration/death-declaration-10.spec.ts
  e2e/testcases/death/declaration/death-declaration-2.spec.ts
  e2e/testcases/death/declaration/death-declaration-3.spec.ts
  e2e/testcases/death/declaration/death-declaration-4.spec.ts
  e2e/testcases/death/declaration/death-declaration-5.spec.ts
  e2e/testcases/death/declaration/death-declaration-6.spec.ts
  e2e/testcases/death/declaration/death-declaration-7.spec.ts
  e2e/testcases/death/declaration/death-declaration-8.spec.ts
  e2e/testcases/death/declaration/death-declaration-9.spec.ts
Labels: ready for merging
