Repository opencrvs/opencrvs-farajaland, pull requests merged in 2024-02, with the labels that each got.

#891 Farajaland certificates updated
  src/api/certificate-configuration/handler.ts
  src/api/fonts/NotoSans-Bold.ttf
  src/data-seeding/certificates/README.md
  src/data-seeding/certificates/handler.ts
  src/data-seeding/certificates/source/BirthCertificate.svg
  src/data-seeding/certificates/source/DeathCertificate.svg
  src/data-seeding/certificates/source/Farajaland-birth-certificate-v2.svg
  src/data-seeding/certificates/source/Farajaland-death-certificate-v2.svg
  src/data-seeding/certificates/source/Farajaland-marriage-certificate-v2.svg
  src/data-seeding/certificates/source/MarriageCertificate.svg
  src/form/birth/certificate-handlebars.ts
  src/form/common/certificate/handlebars/helpers.ts
  src/form/death/certficate-handlebars.ts
Labels: LGTM

#888 Make occupation field usable for deceased
  CHANGELOG.md
  src/form/birth/index.ts
  src/form/common/common-optional-fields.ts
  src/form/death/index.ts
Labels: 💥 Hot Fixes

#805 Farajaland form updates
  src/api/content/client/client.json
  src/form/addresses/index.ts
  src/form/birth/index.ts
  src/form/common/default-validation-conditionals.ts
  src/form/custom-fields.ts
  src/form/death/custom-fields.ts
  src/form/death/index.ts
  src/form/marriage/index.ts
  src/utils/index.ts
Labels: ready for merging

#894 Reason for delayed registration custom form field
  src/api/content/client/client.json
  src/form/addresses/index.ts
  src/form/birth/index.ts
  src/form/custom-fields.ts
  src/form/death/index.ts
Labels: Waiting For Review

#895 add handlebar of age of deceased in death certificate
  src/data-seeding/certificates/source/Farajaland-death-certificate-v2.svg
  src/data-seeding/certificates/source/Farajaland-marriage-certificate-v2.svg
  src/form/common/common-optional-fields.ts
  src/form/death/certficate-handlebars.ts
  src/form/death/index.ts
  src/utils/mapping/field-mapping-utils.ts
Labels: Waiting For Review

#899 ocrvs-6517 Hide fields when informantType not selected
  src/api/content/client/descriptions.json
  src/form/addresses/index.ts
  src/form/death/index.ts
Labels: 💥 Hot Fixes

#905 Update handlebars
  src/form/birth/certificate-handlebars.ts
  src/form/death/certficate-handlebars.ts
  src/form/marriage/certificate-handlebars.ts
Labels: 💥 Hot Fixes
