Repository opencrvs/opencrvs-farajaland, pull requests merged in 2024-05, with the labels that each got.

#974 fix: advanced search end to end test
  cypress/e2e/advancedsearch.spec.ts
Labels: Waiting For Review

#979 fix: Ocrvs 6356- Change condition of Number of previous births
  CHANGELOG.md
  src/form/birth/optional-fields.ts
  src/form/types/types.ts
Labels: LGTM!

#978 feat: generate default address according to user's location
  infrastructure/docker-compose.deploy.yml
  src/constants.ts
  src/form/addresses/address-fields.ts
  src/form/index.ts
  src/form/types/types.ts
  src/utils/address-utils.ts
  src/utils/users.ts
Labels: Waiting For Review

#983 [HOTFIX] Mass email subject & content styles
  src/api/notification/email-templates/index.ts
  src/api/notification/email-templates/other/all-user-notification.html
  src/api/notification/handler.ts
Labels: LGTM!

#980 fix: amend certificate filename
  src/data-seeding/certificates/handler.ts
Labels: LGTM!

#1005 chore!: move configuration options
  src/api/application/application-config-default.ts
  src/form/common/common-optional-fields.ts
Labels: Waiting For Review

#997 Add some basic test framework for birth test section
  e2e/constants.ts
  e2e/helpers.ts
  e2e/testcases/birth/1-birth-event-declaration.spec.ts
  e2e/testcases/birth/2-validate-the-child-details-page.spec.ts
  e2e/testcases/birth/8-validate-declaration-review-page.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-1.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-10.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-2.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-3.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-4.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-5.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-6.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-7.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-8.spec.ts
  e2e/testcases/birth/declarations/birth-declaration-9.spec.ts
  e2e/testcases/birth/helpers.ts
  tsconfig.json
Labels: Waiting For Review

#1013 e2e: marriage
  e2e/helpers.ts
  e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
Labels: LGTM
