Repository opencrvs/opencrvs-farajaland, pull requests merged in 2025-02, with the labels that each got.

#1207 chore: add submit button to save scope in qa editor
  src/data-seeding/roles/qa-scopes-editor.html
Labels: Stale

#1224 Added vadym mudryi to development and e2e servers
  infrastructure/server-setup/inventory/development.yml
  infrastructure/server-setup/inventory/e2e.yml
Labels: ready for merging, 🚀 Ready to deploy

#1225 fix: Added vadym mudryi to opencrvs servers, disabled niko
  infrastructure/server-setup/inventory/backup.yml
  infrastructure/server-setup/inventory/jump.yml
  infrastructure/server-setup/inventory/production.yml
  infrastructure/server-setup/inventory/qa.yml
  infrastructure/server-setup/inventory/staging.yml
Labels: 🚀 Ready to deploy

#1220 Ocrvs event v2 7919 Print Certificate
  src/api/certificates/source/tennis-club-membership-certificate.svg
Labels: 🚀 Ready to deploy
